version: '3'

services:
  ################################
  #   Setup react js container
  ################################
  mysmoothie-react:
    build: .
    ports:
      - 8086:3000
    volumes:
      - ./:/app
  ################################
  #   Setup nginx load balancer
  ################################
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    ports:
      - 80:80 # expose 80 on host and sent to 80 in container
    depends_on:
      - mysmoothie-react
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
