
let FRUITS = [
  { "id": 1, "name": "Abricot", "type": "fruit", "gout": ["sucré"], "preparation": "Dénoyauter et couper l'abricot en quartier" },
  { "id": 2, "name": "Ananas", "type": "fruit", "gout": ["sucré", "acide"], "preparation": "Epeler l'ananas et couper le en tranches ou en dés" },
  { "id": 3, "name": "Avocat", "type": "fruit", "gout": ["salé", "amer"], "preparation": "Dénoyauté et couper l'avocat en dés" },
  { "id": 4, "name": "Banane", "type": "fruit", "gout": ["sucré"], "preparation": "Epelucher et couper le banane en plusieurs tranches" },
  { "id": 5, "name": "Betterave", "type": "legume", "gout": ["salé"], "preparation": "Couper la bétterave cuite en dés" },
  { "id": 6, "name": "Carotte", "type": "legume", "gout": ["salé"], "preparation": "Epelucher et couper la carotte en rondelles" },
  { "id": 7, "name": "Citron jaune", "type": "fruit", "gout": ["salé"], "preparation": "Epelucher et couper le citron en quartier" },
  { "id": 8, "name": "Citron vert", "type": "fruit", "gout": ["salé"], "preparation": "Epelucher et couper le citron en quartier" },
  { "id": 9, "name": "Concombre", "type": "legume", "gout": ["salé"], "preparation": "" },
  { "id": 10, "name": "Concours", "type": "fruit", "gout": ["salé"], "preparation": "" },
  { "id": 11, "name": "Coriandre", "type": "legume", "gout": ["salé"], "preparation": "" },
  { "id": 12, "name": "Figue", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 13, "name": "Fruit de la passion", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 14, "name": "Canneberge", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 15, "name": "Cassis", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 16, "name": "Cerise", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 17, "name": "Fraise", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 18, "name": "Framboise", "type": "fruit", "gout": ["sucré", "acide"], "preparation": "" },
  { "id": 19, "name": "Groseille", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 20, "name": "Mûre", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 21, "name": "myrtille", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 22, "name": "Gingembre", "type": "tubercule", "gout": ["acide", "amer"], "preparation": "" },
  { "id": 23, "name": "Grenade", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 24, "name": "Kaki", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 25, "name": "Kiwi", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 26, "name": "Litchi", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 27, "name": "Mangue", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 28, "name": "Melon", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 29, "name": "Menthe", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 30, "name": "Mirabelle", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 31, "name": "Noix de coco", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 32, "name": "Orange", "type": "fruit", "gout": ["sucré", "acide"], "preparation": "" },
  { "id": 33, "name": "Orange sanguine", "type": "fruit", "gout": ["sucré", "acide"], "preparation": "" },
  { "id": 34, "name": "Pamplemousse", "type": "fruit", "gout": ["sucré", "acide"], "preparation": "" },
  { "id": 35, "name": "Papaye", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 36, "name": "Pastèque", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 37, "name": "Nectarine", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 38, "name": "Pêche blanche", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 39, "name": "Pêche jaune", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 40, "name": "Poire", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 41, "name": "Pomme", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 42, "name": "Raisin", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 43, "name": "Rhubarbe", "type": "legume", "gout": ["salé"], "preparation": "" },
  { "id": 44, "name": "Rose", "type": "fruit", "gout": ["sucré"], "preparation": "" },
  { "id": 45, "name": "Tomate", "type": "fruit", "gout": ["sucré", "acide"], "preparation": "" }
];

export default FRUITS;